version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: car-insurance-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: car-insurance
    volumes:
      - mongo_data:/data/db
    networks:
      - car-insurance-network_be

  # backend:
  #   build: .
  #   container_name: car-insurance-backend
  #   ports:
  #     - "5000:5000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo
  #   networks:
  #     - car-insurance-network
  #   command: npm start

volumes:
  mongo_data:

networks:
  car-insurance-network_be:
